[
  {
    _id: "655cc07eca0cc597d405ec89",
    question: "What is speed of light",
    subject: "physics",
    topic: "waves",
    difficulty: "easy",
    marks: 1,
    __v: 0,
  },
  {
    _id: "655cd545c1731361f764901d",
    question:
      "The HBO series &quot;Game of Thrones&quot; is based on which series of books?",
    subject: "physics",
    topic: "speed",
    difficulty: "medium",
    marks: 5,
    __v: 0,
  },
  {
    _id: "655cd57dc1731361f764901f",
    question: "Deionized water is water with which of the following removed?",
    subject: "chemistry",
    topic: "water",
    difficulty: "medium",
    marks: 5,
    __v: 0,
  },
  {
    _id: "655cd59ac1731361f7649021",
    question: "Type 1 diabetes is a result of the liver working improperly.",
    subject: "biology",
    topic: "disease",
    difficulty: "easy",
    marks: 1,
    __v: 0,
  },
  {
    _id: "655cd5afc1731361f7649023",
    question: "What is radiation measured in?",
    subject: "physics",
    topic: "radiation",
    difficulty: "easy",
    marks: 1,
    __v: 0,
  },
  {
    _id: "655cd69dc1731361f7649025",
    question:
      "In the programming language &quot;Python&quot;, which of these statements would display the string &quot;Hello World&quot; correctly?",
    subject: "computer science",
    topic: "python",
    difficulty: "hard",
    marks: 10,
    __v: 0,
  },
  {
    _id: "655cd6b3c1731361f7649027",
    question: "In what year was McDonald&#039;s founded?",
    subject: "general knowledege",
    topic: "gk",
    difficulty: "hard",
    marks: 10,
    __v: 0,
  },
  {
    _id: "655decfbb1eec6ddbfa89ae0",
    question: "What is ur name",
    subject: "gk",
    topic: "gk",
    difficulty: "easy",
    marks: 1,
    __v: 0,
  },
  {
    _id: "655e7482d0adc82fdbbc7573",
    question: "Who win 2023 worldcup",
    subject: "gk",
    topic: "gk",
    difficulty: "medium",
    marks: 5,
    __v: 0,
  },
  {
    _id: "655f1b9573ed7b13a61efecd",
    question: "Which of the following is used to measure blood pressure?",
    subject: "Science",
    topic: "blood",
    difficulty: "medium",
    marks: 5,
    __v: 0,
  },
  {
    _id: "655f1bca73ed7b13a61efed0",
    question:
      "What cricketing term denotes a batsman being dismissed with a score of zero",
    subject: "Sports",
    topic: "cricket",
    difficulty: "medium",
    marks: 5,
    __v: 0,
  },
  {
    _id: "655f1bff73ed7b13a61efed3",
    question:
      "During World War I, which nation&#039;s monarchs were blood related?",
    subject: "History",
    topic: "world war",
    difficulty: "medium",
    marks: 5,
    __v: 0,
  },
  {
    _id: "655f1c1873ed7b13a61efed6",
    question: "Which Audi does not use Haldex based all wheel drive system?",
    subject: "Vehicles",
    topic: "car",
    difficulty: "medium",
    marks: 5,
    __v: 0,
  },
  {
    _id: "655f1c3073ed7b13a61efed9",
    question: "Nephelococcygia is the practice of doing what",
    subject: "General Knowledge",
    topic: "gk",
    difficulty: "hard",
    marks: 10,
    __v: 0,
  },
  {
    _id: "655f1cc973ed7b13a61efedc",
    question: "What is the approximate value of mathematical constant e",
    subject: "Science",
    topic: "Mathematics",
    difficulty: "hard",
    marks: 10,
    __v: 0,
  },
  {
    _id: "655f1cdd73ed7b13a61efedf",
    question:
      "Which of the following countries does NOT recognize Armenia as an independent country?",
    subject: "Geography",
    topic: "country",
    difficulty: "hard",
    marks: 10,
    __v: 0,
  },
  {
    _id: "655f1cfc73ed7b13a61efee2",
    question: "Which basketball team has attended the most NBA grand finals",
    subject: "Sports",
    topic: " basketball",
    difficulty: "hard",
    marks: 10,
    __v: 0,
  },
  {
    _id: "655f1d1373ed7b13a61efee5",
    question: "What number does the Roman numeral &quot;D&quot; stand for?",
    subject: "maths",
    topic: "roman",
    difficulty: "hard",
    marks: 10,
    __v: 0,
  },
  {
    _id: "655f1d3473ed7b13a61efee8",
    question: "How many zeros are there in a googol",
    subject: "Science",
    topic: "Mathematics",
    difficulty: "hard",
    marks: 10,
    __v: 0,
  },
  {
    _id: "655f1d4573ed7b13a61efeeb",
    question: "What was the first movie to ever use a Wilhelm Scream",
    subject: "Entertainment",
    topic: "Film",
    difficulty: "hard",
    marks: 10,
    __v: 0,
  },
  {
    _id: "655f1d5c73ed7b13a61efeee",
    question: "In the 2012 film, &quot;The Lorax&quot;, who is the antagonist",
    subject: "Entertainment",
    topic: "Film",
    difficulty: "hard",
    marks: 10,
    __v: 0,
  },
  {
    _id: "655f1d7173ed7b13a61efef1",
    question:
      "What year is considered to be the year that the British Empire ended",
    subject: "History",
    topic: "History",
    difficulty: "hard",
    marks: 10,
    __v: 0,
  },
  {
    _id: "655f1d7f73ed7b13a61efef4",
    question: "What does the term GPU stand for?",
    subject: "Science",
    topic: "Computers",
    difficulty: "hard",
    marks: 10,
    __v: 0,
  },
  {
    _id: "655f1d9273ed7b13a61efef7",
    question: "What is the weight of a Gold Bar in Fallout: New Vegas",
    subject: "General Knowledge",
    topic: "gk",
    difficulty: "hard",
    marks: 10,
    __v: 0,
  },
  {
    _id: "655f1daf73ed7b13a61efefa",
    question: "Which souls game was not directed by Hidetaka Miyazaki",
    subject: "Entertainment",
    topic: "Video Games",
    difficulty: "hard",
    marks: 10,
    __v: 0,
  },
  {
    _id: "655f1de073ed7b13a61efefd",
    question:
      '"The Quadrangularis Reversum is best described as which of the following?',
    subject: "General Knowledge",
    topic: "gk",
    difficulty: "hard",
    marks: 10,
    __v: 0,
  },
  {
    _id: "655f1dfb73ed7b13a61eff00",
    question: "What does the term GPU stand for",
    subject: "Science",
    topic: "Computers",
    difficulty: "medium",
    marks: 5,
    __v: 0,
  },
  {
    _id: "655f1ea973ed7b13a61eff03",
    question:
      "The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer",
    subject: "Science",
    topic: "Computers",
    difficulty: "medium",
    marks: 5,
    __v: 0,
  },
  {
    _id: "655f1eb873ed7b13a61eff06",
    question: "n 2015, David Hasselhof released a single called...",
    subject: "Entertainment",
    topic: "Music",
    difficulty: "medium",
    marks: 5,
    __v: 0,
  },
  {
    _id: "655f1ed073ed7b13a61eff09",
    question: "What tiny principality lies between Spain and France",
    subject: "Geography",
    topic: "Geography",
    difficulty: "medium",
    marks: 5,
    __v: 0,
  },
  {
    _id: "655f1ee073ed7b13a61eff0c",
    question:
      "Which of the following battles is often considered as marking the beginning of the fall of the Western Roman Empire?",
    subject: "History",
    topic: "Adrianople",
    difficulty: "medium",
    marks: 5,
    __v: 0,
  },
  {
    _id: "655f1ef073ed7b13a61eff0f",
    question:
      "Who recorded the album called &quot;Down to the Moon&quot; in 1986?",
    subject: "Entertainment",
    topic: "Music",
    difficulty: "medium",
    marks: 5,
    __v: 0,
  },
  {
    _id: "655f1f0c73ed7b13a61eff12",
    question: "what is the world&#039;s most expensive spice by weight?",
    subject: "General Knowledge",
    topic: "General Knowledge",
    difficulty: "medium",
    marks: 5,
    __v: 0,
  },
  {
    _id: "655f1f2373ed7b13a61eff15",
    question: "Which television show has Dan Gheesling been on",
    subject: "enterainment",
    topic: "Celebrities",
    difficulty: "medium",
    marks: 5,
    __v: 0,
  },
  {
    _id: "655f1f5873ed7b13a61eff18",
    question:
      "Sting, the lead vocalist of The Police, primarily plays what instrument",
    subject: "Entertainment",
    topic: "Music",
    difficulty: "easy",
    marks: 1,
    __v: 0,
  },
  {
    _id: "655f1f6b73ed7b13a61eff1b",
    question: "What name is given to all baby marsupials",
    subject: "Science",
    topic: "Nature",
    difficulty: "easy",
    marks: 1,
    __v: 0,
  },
  {
    _id: "655f1f8073ed7b13a61eff1f",
    question: "HTML is what type of language?",
    subject: "Science",
    topic: "Computers",
    difficulty: "easy",
    marks: 1,
    __v: 0,
  },
  {
    _id: "655f1f9373ed7b13a61eff22",
    question: "Who is the lead singer of the British pop rock band Coldplay",
    subject: "Entertainment",
    topic: "Entertainment",
    difficulty: "easy",
    marks: 1,
    __v: 0,
  },
  {
    _id: "655f1fa873ed7b13a61eff25",
    question:
      "In the TV show &#039;M*A*S*H&#039;, what was the nickname of Corporal Walter O&#039;Reilly?",
    subject: "Entertainment",
    topic: "Television",
    difficulty: "easy",
    marks: 1,
    __v: 0,
  },
  {
    _id: "655f1fbe73ed7b13a61eff28",
    question: "Who is the frontman of the band 30 Seconds to Mars",
    subject: "Entertainment",
    topic: "Music",
    difficulty: "easy",
    marks: 1,
    __v: 0,
  },
  {
    _id: "655f1fd173ed7b13a61eff2b",
    question: '"Which team won 2014 FIFA World Cup in Brazil?"',
    subject: "Sports",
    topic: "football",
    difficulty: "easy",
    marks: 1,
    __v: 0,
  },
  {
    _id: "655f1fe373ed7b13a61eff2e",
    question: "When did the Battle of the Somme begin",
    subject: "History",
    topic: "History",
    difficulty: "easy",
    marks: 1,
    __v: 0,
  },
  {
    _id: "655f1ff673ed7b13a61eff31",
    question: "What colour is the circle on the Japanese flag",
    subject: "Geography",
    topic: "Geography",
    difficulty: "easy",
    marks: 1,
    __v: 0,
  },
  {
    _id: "655f201873ed7b13a61eff34",
    question: "A universal set, or a set that contains all sets, exists.",
    subject: "Science",
    topic: "Mathematics",
    difficulty: "easy",
    marks: 1,
    __v: 0,
  },
  {
    _id: "655f203073ed7b13a61eff37",
    question: "What ingredients are required to make a cake in Minecraft",
    subject: "Entertainment",
    topic: "Video Games",
    difficulty: "easy",
    marks: 1,
    __v: 0,
  },
  {
    _id: "655f204873ed7b13a61eff3a",
    question:
      "In Two and a Half Men, what is Alan Harper&#039;s son&#039;s name",
    subject: "Entertainment",
    topic: "Television",
    difficulty: "easy",
    marks: 1,
    __v: 0,
  },
  {
    _id: "655f207b73ed7b13a61eff3d",
    question:
      '"Which of the following did not feature in the cartoon &#039;Wacky',
    subject: "Entertainment",
    topic: "Cartoon",
    difficulty: "easy",
    marks: 1,
    __v: 0,
  },
  {
    _id: "655f209f73ed7b13a61eff40",
    question: "Entertainment",
    subject: "Japanese",
    topic:
      "Future Diary&quot;, what is the name of Yuno Gasai&#039;s Phone Diary",
    difficulty: "easy",
    marks: 1,
    __v: 0,
  },
  {
    _id: "655f20b173ed7b13a61eff43",
    question:
      "The movie &quot;The Nightmare before Christmas&quot; was all done with physical objects",
    subject: "Entertainment",
    topic: "Film",
    difficulty: "easy",
    marks: 1,
    __v: 0,
  },
  {
    _id: "655f20ca73ed7b13a61eff46",
    question: "Which of these countries remained neutral during World War II",
    subject: "History",
    topic: "History",
    difficulty: "easy",
    marks: 1,
    __v: 0,
  },
  {
    _id: "655f20df73ed7b13a61eff49",
    question:
      "Which member of the Foo Fighters was previously the drummer for Nirvana",
    subject: "Entertainment",
    topic: "Music",
    difficulty: "easy",
    marks: 1,
    __v: 0,
  },
];
